## # 手工实现 One-hot 编码

In [ ]:
words = ["apple", "banana", "orange", "apple"]

# 构建词典
vocab = sorted(set(words))
word_to_index = {word: idx for idx, word in enumerate(vocab)}
print("词典:", word_to_index)

# 构建 One-hot 向量
onehot_vectors = []
for word in words:
    vector = [0] * len(vocab)
    vector[word_to_index[word]] = 1
    onehot_vectors.append(vector)
# 输出结果
for w, vec in zip(words, onehot_vectors):
    print(f"{w}: {vec}")


## scikit-learn one-hot 编码

In [4]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# 原始数据
words = np.array(["apple", "banana", "orange", "apple"]).reshape(-1, 1)

# 初始化 OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)  # sparse=False 返回数组而不是稀疏矩阵

# 拟合并转换
onehot_vectors = encoder.fit_transform(words)

# 打印词典和向量
print("类别顺序:", encoder.categories_)
print(onehot_vectors)


类别顺序: [array(['apple', 'banana', 'orange'], dtype='<U6')]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


## torch实现 one-hot 编码

In [ ]:
import torch
import torch.nn.functional as F

# 词表和词索引
words = ["apple", "banana", "orange", "apple"]
vocab = sorted(set(words))
word_to_index = {word: idx for idx, word in enumerate(vocab)}

# 将词转换为索引
indices = torch.tensor([word_to_index[word] for word in words])
print("索引:", indices)

# 生成 One-hot 向量
onehot = F.one_hot(indices, num_classes=len(vocab))
print("One-hot 向量:\n", onehot)


## 手工用张量构建

In [ ]:
import torch

# 索引
indices = torch.tensor([0, 1, 2, 0])
vocab_size = 3

# 初始化全 0 张量
onehot = torch.zeros((indices.size(0), vocab_size), dtype=torch.long)

# 根据索引设置 1
onehot[torch.arange(indices.size(0)), indices] = 1
print("手工 One-hot:\n", onehot)
